services:
  - type: web
    name: subaselvi-motors-billing
    env: node
    plan: starter # Starter plan is required to use Persistent Disks
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
